name: News digest (にじさんじ)

on:
  schedule:
    - cron: "40 23 * * *"
  workflow_dispatch:
    inputs:
      topic:
        description: "トピック"
        required: false
        default: "にじさんじ"

jobs:
  run-digest:
    uses: ./.github/workflows/reusable-news-digest.yml
    with:
      name: "にじさんじ"
      topic: ${{ github.event.inputs.topic || 'にじさんじ' }}
    secrets: inherit
